image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu20.04:latest

stages:
  - build
  - pages

autoconf:
  stage: build
  script:
    - sh build/gitlab-ci autoconf
  after_script:
    - 'cat autoconf-build/test/test-suite.log'

cmake-makefiles:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Unix Makefiles" Release

cmake-ninja:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Ninja" Debug

pages:
  stage: pages
  script:
    - cp -r html public
  artifacts:
    name: $CI_PROJECT_NAME-$CI_JOB_NAME
    paths:
    - public
  only:
  - master
